USE_EB = TRUE

ebase = navierDriver

#CHOMBO_HOME = /work/02138/siddarth/lonestar/CHOMBO/Chombo-3.2/lib
CHOMBO_HOME = /work/02138/siddarth/CHOMBO/Chombo-3.2/lib
#CHOMBO_HOME = /home/siddarth/CHOMBO/SFD_CHOMBOlib

LibNames = EBAMRTimeDependent EBAMRElliptic EBAMRTools Workshop EBTools AMRElliptic AMRTimeDependent AMRTools BoxTools
base_dir = .
src_dirs = ../src/ ../../SFD/libSFD ../../SFD/srcSFD

INPUT = ramp.2d.inputs

include $(CHOMBO_HOME)/mk/Make.example

