USE_EB = TRUE

ebase = stabilityDriver

#CHOMBO_HOME = /work/02138/siddarth/lonestar/CHOMBO/Chombo-3.2/lib
CHOMBO_HOME = /work/02138/siddarth/CHOMBO/Chombo-3.2/lib
#CHOMBO_HOME = /home/siddarth/CHOMBO/SFD_CHOMBOlib

LibNames = EBAMRTimeDependent EBAMRElliptic EBAMRTools Workshop EBTools AMRElliptic AMRTimeDependent AMRTools BoxTools
base_dir = .
src_dirs = ../libStability/ ../SFD/libSFD ../SFD/srcSFD ../solvers/EBAMRINS/src ../solvers/EBAMRINS/srcLib

INPUT = ramp.2d.inputs

include $(CHOMBO_HOME)/mk/Make.example

