#!/bin/bash
                          # Use Bash Shell

#SBATCH -J test          #Job name
#SBATCH -o test.%j.out   # stdout; %j expands jobid
#SBATCH -e test.%j.err   # stderr; skip to combine stdout and stderr
#SBATCH -p development        # queue
#SBATCH -N 1              # Number of nodes, not cores (16 cores/node)
#SBATCH -n 16             # Total number of MPI tasks (if omitted, n=N)
#SBATCH -t 00:05:00       # max time

#SBATCH --mail-user=siddarth.chintamani@mavs.uta.edu
#SBATCH --mail-type=ALL

#SBATCH -A Global-Stability-of

                          # Run the MPI executable named "addexe"
ibrun ./stabilityDriver2d.Linux.64.mpicxx.ifort.DEBUG.MPI.ex sphere.inputs
